### ISSUE TITLE
Enable UI customization

### ISSUE THREAD

**Issue by fatmali** [fatmali/react-formik-wizard#5]

**Comment by redarccoder** [comment]
I don't know if this is usefull, but, I have another formik wizard proyect up on NPM (Have not created the github page or really optimized it yet).

If you want to take a look it is on: https://www.npmjs.com/package/yeaformikwizard

**Comment by fatmali** [comment]
Hi @redarccoder , thanks! Had a look at your solution and it's great. The key difference is that I want to implement this using JSON/a serializable object that can then be transferred over the network i.e to enable forms to have the flexibility of  living within or outside the app.

**Comment by redarccoder** [comment]
> 
> 
> Hi @redarccoder , thanks! Had a look at your solution and it's great. The key difference is that I want to implement this using JSON/a serializable object that can then be transferred over the network i.e to enable forms to have the flexibility of living within or outside the app.

I guess we could achive that using some wrapping of the object (in the same style that I customized the wizard), but, to correctly render it, it would need to accept custom properties (like container, container class, component, className, etc...).

Using the "as" property of "Field" you can render the component as another (in the example they render <Field as="select" />, you could render the components that way.

A more concrete example of this could be:

```javascript
const Component = ({  }) => (
    const Fields = [{ name: "name", parent: "div" parentProps: {className: "card-body"} fieldProps {className:"form-control"} }]
    return (
        <Formik>
            <Form>
                { Fields.map(field => {
                    if(field.parent) return (<field.parent {...field.parentProps}><Field {...field.fieldprops} /><field.parent />)
                    return (<Field {field.fieldProps} />)
                })}
            </Form>
        </Formik>
    )
)
```

Obviously this needs a lot of work to enable the passing of properties and correct parent rendering. Also, in the properties you can add the validation properties and generate functions based on them.

If i´m not wrong, I did exactly this a few years ago (with jQuery and .validate to have form validation). Let me revive my old laptop and Ill post that code here.

**Comment by fatmali** [comment]
This solution makes sense and it would work for the use case. The upside would be users would be able to define their own custom components, however I see two downsides with this approach:
1. Defining custom components like this to be rendered is going to be unnatural for the user, for example how would she write DOM elements for a field nested within each other - writing it in JSX would be way simpler
2. It's going to be a lot of work to write this functionality 😃 

Perhaps an easier way of doing this would be to let form and field structure and validations to defined in JSON, and customization of the UI to be handled by the component rendering the form itself, as the component itself is in JSX. For this we would utilize the `render prop` of the formik field which would pass needed props to the custom component. For example:

```jsx
import CustomInput from './custom/input';

const Component = () => {

    // json representing the form
    const Fields = [{ name: "name",  type: "select", options: []}...];


    // Assume <Wizard/> is a component that knows how to build and render a form using the fields as json
    // it accepts as params:
    // the fields as json
    // the custom components as an object
    // a directive instructing the wizard to use this custom component
    return (
        <Wizard fields={fields} customComponents={{ input: CustomInput }}  useCustom />
    )
}
```

and then CustomInput can be defined as:

```jsx
const CustomInput = {({ field, form, meta }) => (
   <div>
     <input type="text" {...field} />
     {meta.touched &&
       meta.error && <div className="error">{meta.error}</div>}
   </div>
 )}
```

Curious to know your thoughts about this :-) @redarccoder

**Comment by redarccoder** [comment]
This seems like a good i dea, the only change I would make is to write components this way:
```javascript
import React, {useState} from 'react'
import { Field } from 'formik'
const CustomComponent = ({ someProps }) => (
<Field>
({ field }) => (
    <input { ...field } />
)
</Field>
)
```
If you do it this way there is no need to pass the meta object, anoter way to do it would be to let the Formik object to pass the properties directly, then automatically call the values directly to the Component.
```javascript
import React, { useState } from 'react';
import { Formik } from 'formik';

const BasicExample = ({ cbFunction, cbCancel }) => { 
const [state, setState] = useState({ data:{}, currentStep: 0 })
const steps = [
    { name:"1", initialValues: {}, controls: [{ name: 'nm1', props: {}, validation:{}, ctrl:()=> (<input />) }, { name: 'nm2', props: {}, validation:{}, ctrl:"" }
,   { name:"2", initialValues: {},, controls: [{ name: 'nn1', props: {}, validation:{}, ctrl:"" }] }
]

// dummy function to render
const CustomControl({ control, values, handleChange  }) => {
    const { name, props, validation, ctrl as Control  } = control
    return (<Field as={Control}) name={name} {...props} />)
}

return (
   <div>
     <Formik
       key={state.currentStep}
       initialValues={steps[state.currentStep]}
       onSubmit={(values, actions) => {
         // handle next or finish, etc....
         cbFunction(values);
       }}
     >
       {props => (
         <form onSubmit={props.handleSubmit}>

           {steps[state.currentStep].controls.map(ctrl => (
                 <CustomControl  control={ctrl} values={props.values} handleChange={props.handleChange} />
           )} 

           <button type="submit">Submit</button>

         </form>

       )}

     </Formik>

   </div>
 );
}
```
This way you can render custom controls, but it's way more complicated, since you can inherit everything from Field.

BTW, I have not tested this, but, it should work... ?

**Comment by fatmali** [comment]
> This seems like a good idea, the only change I would make is to write components this way:
> 
> ```js
> import React, {useState} from 'react'
> import { Field } from 'formik'
> const CustomComponent = ({ someProps }) => (
> <Field>
> ({ field }) => (
>     <input { ...field } />
> )
> </Field>
> )
> ```

Well this doesn't seem ideal because of two reasons:
1. This would mean that the user of this library also needs to install `Formik` as a dependency. `CustomInput` is defined outside the library and not within it.
2. Remember this library defines the `Formik` instance  as well as the fields `<Field>`, and the `meta` props are being passed down from the `<Field />` to it's children automatically.

>BTW, I have not tested this, but, it should work... ?

It would.

>Lastly, unless you're planning to automate something (had a project like that), I see no point in changing the way people write Formik forms (using in over a year I can write a form in less than 5 minutes, using other controls and helpers in my project), that's why In the plugin I wrote we write the JSX directly, that way you can add subtitles, sub-components, info using the data and so on.

This library doesn't aim to change the way people write Formik forms, Rather aims to provide them with a quick and flexible way to do it. It might not be ideal if your forms are simple enough to craft in 5 minutes, it helps when you have multisectional, dynamic and ever changing form that you might want to have a separate release cycle from your app.
